# Change these first
owner: its0din-ai # Your GitHub organization or username, where this repository lives
repo: uptime-stats # The name of this repository
useragent: "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.126 Mobile Safari/537.36 (compatible; encrypt0rbot/1.1; +https://encrypt0r.my.id/)"

sites:
  - name: Main Sites
    url: https://encrypt0r.my.id
  - name: ID Server
    url: $ID_SRV
    port: 4321
    check: "tcp-ping"
  - name: JP Server
    url: $JP_SRV
    port: 4321
    check: "tcp-ping"
  - name: CyberChef
    url: https://chef.encrypt0r.my.id
  - name: Blogs
    url: https://blog.encrypt0r.my.id
  - name: Ethereum Gateway
    url: https://eth.encrypt0r.my.id
  - name: Microsoft Activation Scripts (MAS) Mirror
    url: https://scripts.encrypt0r.my.id/mas
    method: GET

status-website:
  theme: light
  cname: status.encrypt0r.my.id
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: encrypt0r Infrastructure Status
  introTitle: "encrypt0r Infrastructure Status"
  introMessage: This is a status page for all encrypt0r's network infrastructure
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Main Page
      href: https://encrypt0r.my.id/
