# Change these first
owner: its0din-ai # Your GitHub organization or username, where this repository lives
repo: uptime-stats # The name of this repository
useragent: "encrypt0rBot/1.1; (+https://encrypt0r.my.id/)"

sites:
  - name: Main Sites
    url: https://encrypt0r.my.id
  - name: DoT
    url: 5qr0naarye.cloudflare-gateway.com
    check: "tcp-ping"
  - name: DoH
    url: https://5qr0naarye.cloudflare-gateway.com/dns-query
    expectedStatusCodes:
      - 200
      - 400
  - name: ID Arsenal-1 [🇮🇩]
    url: $ID_SRV
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png
    port: 4321
    check: "tcp-ping"
  - name: ID WAN [🇮🇩]
    url: $ID_WAN
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png
    port: 4321
    check: "tcp-ping"
  - name: JP Server [🇯🇵]
    url: $JP_SRV
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png
    port: 4321
    check: "tcp-ping"
  - name: SysReptor
    url: https://reporting.encrypt0r.my.id
  - name: CyberChef
    url: https://chef.encrypt0r.my.id
  - name: Blogs
    url: https://blog.encrypt0r.my.id
  - name: Ethereum Gateway
    url: https://eth.encrypt0r.my.id
  - name: Microsoft Activation Scripts (MAS) Mirror
    url: https://scripts.encrypt0r.my.id/mas
    method: GET

status-website:
  theme: light
  cname: status.encrypt0r.my.id
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: encrypt0r Infrastructure Status
  introTitle: "encrypt0r Infrastructure Status"
  introMessage: This is a status page for all encrypt0r's network infrastructure
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Main Page
      href: https://encrypt0r.my.id/
